freebsd_instance:
  image: freebsd-12-0-release-amd64
task:
  name: FreeBSD
  env:
    matrix:
      - JULIA_MathPhysicalConstants_BUILD_SOURCE: "false"
        JULIA_VERSION: 1.0
      - JULIA_MathPhysicalConstants_BUILD_SOURCE: "true"
        JULIA_VERSION: 1.0
      - JULIA_MathPhysicalConstants_BUILD_SOURCE: "false"
        JULIA_VERSION: 1.1
      - JULIA_MathPhysicalConstants_BUILD_SOURCE: "true"
        JULIA_VERSION: 1.1
      - JULIA_MathPhysicalConstants_BUILD_SOURCE: "false"
        JULIA_VERSION: nightly
      - JULIA_MathPhysicalConstants_BUILD_SOURCE: "true"
        JULIA_VERSION: nightly
  install_script:
    - if [ "${JULIA_MathPhysicalConstants_BUILD_SOURCE}" = "true" ]; then pkg install -y gmake gcc; fi
    - sh -c "$(fetch https://raw.githubusercontent.com/laguer/CirrusCI.jl/master/bin/install.sh -o -)"
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
