desc = "Mathematical Physical Constants."
keywords = ["math", "physical", "constant", "codata"]
name = "MathPhysicalConstants"
repo = "https://github.com/LaGuer/MathPhysicalConstants.jl.git"
author = "La Guer"
license = "MIT"
version = "v0.0.2"


[targets]
test = ["Test"]

[compat]
Julia = ">= v0.6"
